# Generated by Django 4.2.27 on 2026-01-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='csr_focus',
            field=models.CharField(blank=True, choices=[('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('ENVIRONMENT', 'Environment'), ('INFRASTRUCTURE', 'Infrastructure'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
