# Generated by Django 4.2.27 on 2026-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_csr_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='primary_kra',
            field=models.CharField(choices=[('SOCIO_ECONOMIC', 'Socio-Economic Development'), ('REPUTATION', 'Corporate Brand Reputation'), ('FINANCIAL', 'Financial Sustainability'), ('OPERATIONAL', 'Operational Excellence')], default='SOCIO_ECONOMIC', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='thematic_area',
            field=models.CharField(choices=[('EDUCATION', 'Education & Skills'), ('HEALTH', 'Health'), ('WASH', 'Water, Sanitation & Hygiene'), ('AGRICULTURE', 'Agriculture'), ('ENVIRONMENT', 'Environment & Climate'), ('ENERGY', 'Energy & Infrastructure'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='ZMW', max_length=3),
        ),
    ]
