# Generated by Django 4.2.27 on 2026-02-01 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('projects', '0003_project_primary_kra_project_thematic_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assigned_team',
            field=models.ManyToManyField(blank=True, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='partner_projects', to='core.organization'),
        ),
    ]
