# Generated by Django 4.2.27 on 2026-02-02 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='target_percent',
            field=models.DecimalField(decimal_places=2, help_text='Physical completion % required', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='value_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
