# Generated by Django 4.2.27 on 2026-02-02 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_beneficiaryfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('year_of_birth', models.IntegerField(blank=True, null=True)),
                ('contact_info', models.CharField(blank=True, help_text='Phone or Email', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Village/Community', max_length=255)),
                ('is_vulnerable', models.BooleanField(default=False, help_text='Disabled, Elderly, Child-headed household etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiaryfeedback',
            name='beneficiary_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_items', to='projects.beneficiary'),
        ),
    ]
