# Generated by Django 4.2.27 on 2026-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_milestone_value_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='disability_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='residence_type',
            field=models.CharField(blank=True, choices=[('URBAN', 'Urban'), ('RURAL', 'Rural'), ('PERI_URBAN', 'Peri-urban')], max_length=20),
        ),
        migrations.AddField(
            model_name='beneficiary',
            name='vulnerability_category',
            field=models.CharField(blank=True, choices=[('ELDERLY', 'Elderly'), ('ORPHAN', 'Orphan'), ('DISABLED', 'Disabled'), ('LOW_INCOME', 'Low Income'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='thematic_area',
            field=models.CharField(choices=[('EDUCATION', 'Education & Skills'), ('HEALTH', 'Health'), ('WASH', 'Water, Sanitation & Hygiene'), ('AGRICULTURE', 'Agriculture'), ('ENVIRONMENT', 'Environment & Climate'), ('ENERGY', 'Energy & Infrastructure'), ('GENDER_EQUALITY', 'Gender Equality & Empowerment'), ('CLIMATE_ADAPTATION', 'Climate Change Adaptation'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
