# Generated by Django 4.2.27 on 2026-02-04 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_beneficiary_disability_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDG',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='e.g. SDG1', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#000000', max_length=7)),
            ],
            options={
                'verbose_name': 'Sustainable Development Goal',
                'verbose_name_plural': 'Sustainable Development Goals',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sdgs',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.sdg'),
        ),
    ]
