# Generated by Django 4.2.7 on 2026-02-05 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_sdg_project_sdgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcomment',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Turn this comment into a task by assigning it to someone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
