# Generated by Django 4.2.27 on 2026-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_projectcomment_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiaryfeedback',
            name='age_group',
            field=models.CharField(blank=True, choices=[('0-14', '0-14'), ('15-24', '15-24'), ('25-64', '25-64'), ('65+', '65+')], max_length=10),
        ),
        migrations.AddField(
            model_name='beneficiaryfeedback',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('PNTS', 'Prefer not to say')], max_length=20),
        ),
        migrations.AddField(
            model_name='beneficiaryfeedback',
            name='location_coords',
            field=models.CharField(blank=True, help_text='Lat,Lng string', max_length=100),
        ),
    ]
