# Generated by Django 4.2.27 on 2026-02-05 13:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_beneficiaryfeedback_age_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategicTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text="Short code e.g. 'WASH'", max_length=50, unique=True)),
                ('color', models.CharField(default='#CCCCCC', help_text='Hex color for UI tags', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.strategictheme'),
        ),
    ]
