# Generated by Django 4.2.27 on 2026-02-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_strategictheme_project_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='catchment_area',
            field=models.JSONField(blank=True, help_text="GeoJSON Polygon defining the project's service area", null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.JSONField(blank=True, help_text='Expected GeoJSON point (Center)', null=True),
        ),
    ]
