# Generated by Django 4.2.29 on 2026-03-30 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0017_project_created_at_project_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='chiefdom',
            field=models.CharField(blank=True, help_text='Chiefdom/ward where works are executed', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_number',
            field=models.CharField(blank=True, help_text='e.g. KGLCDC/2026/001', max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(choices=[('WORKS', 'Works'), ('SUPPLY', 'Supply of Goods'), ('SERVICE', 'Service'), ('CONSULTANCY', 'Consultancy')], default='WORKS', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='defects_liability_period',
            field=models.PositiveIntegerField(default=365, help_text='Defects liability period in days after completion'),
        ),
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='e.g. 30 days from certified invoice'),
        ),
        migrations.AddField(
            model_name='contract',
            name='retention_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Retention % withheld until defects liability period ends', max_digits=5),
        ),
        migrations.AddField(
            model_name='contract',
            name='scope_of_works',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('CLOSED', 'Closed'), ('EXPIRED', 'Expired')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_type', models.CharField(choices=[('EXTENSION', 'Time Extension'), ('VARIATION', 'Variation Order'), ('SCOPE_CHANGE', 'Scope Change'), ('VALUE_ADJUSTMENT', 'Value Adjustment')], max_length=20)),
                ('amendment_number', models.PositiveIntegerField(help_text='Sequential amendment number')),
                ('description', models.TextField()),
                ('original_end_date', models.DateField(blank=True, null=True)),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('original_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='contract_amendments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='projects.contract')),
            ],
            options={
                'ordering': ['contract', 'amendment_number'],
                'unique_together': {('contract', 'amendment_number')},
            },
        ),
    ]
