# Generated by Django 4.2.29 on 2026-03-31 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_contract_enhancement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('contract_type', models.CharField(choices=[('WORKS', 'Works'), ('SUPPLY', 'Supply of Goods'), ('SERVICE', 'Service'), ('CONSULTANCY', 'Consultancy')], default='WORKS', max_length=20)),
                ('default_scope_of_works', models.TextField(blank=True, help_text='Boilerplate scope text pre-filled on new contracts')),
                ('default_payment_terms', models.TextField(blank=True, help_text='Boilerplate payment terms')),
                ('default_retention_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('default_defects_liability_period', models.PositiveIntegerField(default=365, help_text='Days')),
                ('default_milestones', models.JSONField(blank=True, default=list, help_text='List of {title, description, target_percent, value_fraction} objects')),
                ('document', models.FileField(blank=True, help_text='Optional template document (DOCX/PDF)', null=True, upload_to='contract_templates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template this contract was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='projects.contracttemplate'),
        ),
    ]
