# Generated by Django 4.2.27 on 2026-01-30 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='evidence/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('PHOTO', 'Photo'), ('DOCUMENT', 'Document'), ('VIDEO', 'Video')], max_length=10)),
                ('metadata', models.JSONField(default=dict, help_text='EXIF, Timestamp, etc')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inspected_at', models.DateTimeField()),
                ('form_data', models.JSONField(default=dict)),
                ('location', models.JSONField(blank=True, help_text='Expected GeoJSON point', null=True)),
                ('quality_verdict', models.CharField(choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('CONDITIONAL', 'Conditional Pass')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
