# Generated by Django 4.2.27 on 2026-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='icare_compliance',
            field=models.JSONField(default=dict, help_text='I-CARE Values Checklist'),
        ),
    ]
