# Generated by Django 4.2.27 on 2026-02-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_inspection_icare_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='image_hash',
            field=models.CharField(blank=True, help_text='Perceptual Hash for duplicate detection', max_length=64, null=True),
        ),
    ]
