# Generated by Django 4.2.27 on 2026-02-02 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_evidence_image_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='assessments.inspection'),
        ),
    ]
