# Generated by Django 4.2.27 on 2026-02-02 20:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0009_beneficiary_beneficiaryfeedback_beneficiary_profile'),
        ('assessments', '0005_alter_evidence_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostProjectEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sustainability_rating', models.IntegerField(help_text='1 (Poor) to 5 (Excellent) likelihood of sustained impact', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('lessons_learned', models.TextField()),
                ('future_recommendations', models.TextField()),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_project_evaluation', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactFollowUp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='6-Month Follow-up', max_length=100)),
                ('scheduled_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='PENDING', max_length=20)),
                ('outcomes_verified', models.TextField(blank=True, help_text='Summary of sustained outcomes observed')),
                ('notes', models.TextField(blank=True)),
                ('conducted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impact_followups', to='projects.project')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
