# Generated by Django 4.2.27 on 2026-02-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='resolution_summary',
            field=models.TextField(blank=True, help_text='Explanation of how the grievance was resolved'),
        ),
    ]
