# Generated by Django 4.2.27 on 2026-02-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_grievance_resolution_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
    ]
