# Generated by Django 4.2.27 on 2026-02-05 13:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_grievance_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='impact_analyst_notes',
            field=models.TextField(blank=True, help_text='Notes from Impact Analyst verification'),
        ),
        migrations.AddField(
            model_name='grievance',
            name='impact_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='resolution_impact_score',
            field=models.IntegerField(blank=True, help_text='Score (1-5) on how effectively the resolution improved community conditions', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
