# Generated by Django 4.2.27 on 2026-01-30 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentclaim',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentclaim',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
