# Generated by Django 4.2.27 on 2026-01-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('finance', '0002_paymentclaim_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentclaim',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='claims', to='projects.milestone'),
        ),
    ]
