# Generated by Django 4.2.27 on 2026-02-01 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_alter_paymentclaim_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentclaim',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
