# Generated by Django 4.2.27 on 2026-02-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_paymentclaim_prepared_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentclaim',
            name='risk_factors',
            field=models.JSONField(blank=True, default=dict, help_text='Explanation for the risk score'),
        ),
        migrations.AddField(
            model_name='paymentclaim',
            name='risk_score',
            field=models.FloatField(blank=True, help_text='AI calculated risk score (0-100)', null=True),
        ),
    ]
