# Generated by Django 4.2.27 on 2026-02-02 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_claimcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentclaim',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
