# Generated by Django 4.2.27 on 2026-02-02 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_milestone_target_percent_and_more'),
        ('assessments', '0004_evidence_image_hash'),
        ('grievances', '0003_grievance_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investigation',
            options={'ordering': ['-opened_at'], 'verbose_name': 'Investigation', 'verbose_name_plural': 'Investigations'},
        ),
        migrations.AlterModelOptions(
            name='investigationevidence',
            options={'ordering': ['-added_at'], 'verbose_name': 'Investigation Evidence Link', 'verbose_name_plural': 'Investigation Evidence Links'},
        ),
        migrations.RenameField(
            model_name='investigation',
            old_name='end_date',
            new_name='target_resolution_date',
        ),
        migrations.RenameField(
            model_name='investigationevidence',
            old_name='uploaded_at',
            new_name='added_at',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='grievance',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='investigation',
            name='summary',
        ),
        migrations.AddField(
            model_name='investigation',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_investigations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigation',
            name='category',
            field=models.CharField(choices=[('QUALITY', 'Quality Issue'), ('COMPLIANCE', 'Compliance Violation'), ('SAFETY', 'Safety Incident'), ('FRAUD', 'Suspected Fraud'), ('ENVIRONMENTAL', 'Environmental Concern'), ('GRIEVANCE', 'Grievance Investigation'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='investigation',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='corrective_actions',
            field=models.JSONField(blank=True, default=list, help_text='List of corrective actions taken'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investigations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigation',
            name='description',
            field=models.TextField(default='No description provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigation',
            name='estimated_impact',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated financial impact', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='opened_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='related_grievance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigations', to='grievances.grievance'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='resolution_summary',
            field=models.TextField(blank=True, help_text='Summary of how the investigation was resolved'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investigation',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='investigation',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='investigation',
            name='title',
            field=models.CharField(default='Untitled Investigation', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investigation',
            name='triggered_by_inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_investigations', to='assessments.inspection'),
        ),
        migrations.AddField(
            model_name='investigationevidence',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investigationevidence',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='assessments.evidence'),
        ),
        migrations.AddField(
            model_name='investigationevidence',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about why this evidence is relevant'),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='investigator',
            field=models.ForeignKey(blank=True, help_text='Legacy field - use assigned_to instead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_investigations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='investigationevidence',
            name='investigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_evidence', to='investigations.investigation'),
        ),
        migrations.AlterUniqueTogether(
            name='investigationevidence',
            unique_together={('investigation', 'evidence')},
        ),
        migrations.CreateModel(
            name='InvestigationUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('update_type', models.CharField(choices=[('NOTE', 'Note Added'), ('STATUS_CHANGE', 'Status Changed'), ('EVIDENCE_ADDED', 'Evidence Added'), ('ASSIGNMENT_CHANGE', 'Assignment Changed'), ('RESOLUTION', 'Resolution Added'), ('REOPENED', 'Investigation Reopened')], default='NOTE', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment file paths')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata like previous/new values')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='investigations.investigation')),
            ],
            options={
                'verbose_name': 'Investigation Update',
                'verbose_name_plural': 'Investigation Updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='investigationevidence',
            name='description',
        ),
        migrations.RemoveField(
            model_name='investigationevidence',
            name='file',
        ),
        migrations.RemoveField(
            model_name='investigationevidence',
            name='uploaded_by',
        ),
    ]
