# Generated by Django 4.2.27 on 2026-02-03 20:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('investigations', '0002_alter_investigation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestigationMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='investigations.investigation')),
            ],
            options={
                'verbose_name': 'Investigation Milestone',
                'verbose_name_plural': 'Investigation Milestones',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
