from django.http import HttpResponse
from django.db import models
from django.shortcuts import get_object_or_404
from rest_framework import viewsets, permissions, status
from rest_framework.decorators import action
from .models import CustomReport
from .serializers import CustomReportSerializer
import csv
import io
from openpyxl import Workbook
from openpyxl.styles import Font, Alignment, PatternFill
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

class CustomReportViewSet(viewsets.ModelViewSet):
    queryset = CustomReport.objects.all()
    serializer_class = CustomReportSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        # Users can see their own reports and public reports
        return CustomReport.objects.filter(
            models.Q(created_by=self.request.user) | models.Q(is_public=True)
        )

    def perform_create(self, serializer):
        serializer.save(created_by=self.request.user)

    @action(detail=True, methods=['get'])
    def export(self, request, pk=None):
        report = self.get_object()
        fmt = request.GET.get('format', 'csv')
        user = request.user

        if fmt == 'csv':
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = f'attachment; filename="{report.title}.csv"'
            
            writer = csv.writer(response)
            writer.writerow(['Report Title', report.title])
            writer.writerow(['Description', report.description or ''])
            writer.writerow([])
            writer.writerow(['Component', 'Type', 'Config'])
            
            components = report.layout_config.get('components', [])
            for comp in components:
                writer.writerow([comp.get('label', 'Untitled'), comp.get('type', 'Unknown'), str(comp.get('config', {}))])
                
            return response
            
        elif fmt == 'xlsx':
            response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
            response['Content-Disposition'] = f'attachment; filename="{report.title}.xlsx"'
            
            wb = Workbook()
            ws = wb.active
            ws.title = "Report"
            
            # Styles
            header_font = Font(bold=True, color="FFFFFF")
            header_fill = PatternFill(start_color="1A4D2E", end_color="1A4D2E", fill_type="solid")
            center_align = Alignment(horizontal="center")
            
            # Header Info
            ws.append(['MonEva - Strategic Reporting System'])
            ws.append(['Report Title:', report.title])
            ws.append(['Generated By:', user.username])
            ws.append(['Description:', report.description or ''])
            ws.append([]) # Spacer
            
            # Table Header
            headers = ['Component Label', 'Type', 'Configuration Detail']
            ws.append(headers)
            
            # Apply header styles (6th row is headers)
            for cell in ws[6]:
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = center_align
                
            # Data
            components = report.layout_config.get('components', [])
            for comp in components:
                ws.append([
                    comp.get('label', 'Untitled'),
                    comp.get('type', 'Unknown'),
                    str(comp.get('config', {}))
                ])
                
            # Column Widths
            ws.column_dimensions['A'].width = 30
            ws.column_dimensions['B'].width = 20
            ws.column_dimensions['C'].width = 60
            
            wb.save(response)
            return response

        elif fmt == 'pdf':
            response = HttpResponse(content_type='application/pdf')
            response['Content-Disposition'] = f'attachment; filename="{report.title}.pdf"'
            
            buffer = io.BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter)
            styles = getSampleStyleSheet()
            elements = []
            
            # Title
            elements.append(Paragraph(f"MonEva Strategic Report: {report.title}", styles['Title']))
            elements.append(Spacer(1, 12))
            
            # Metadata
            elements.append(Paragraph(f"<b>Generated By:</b> {user.username}", styles['Normal']))
            elements.append(Paragraph(f"<b>Description:</b> {report.description or 'No description provided.'}", styles['Normal']))
            elements.append(Spacer(1, 24))
            
            # Component Table
            data = [['Component', 'Type', 'Config Summary']]
            components = report.layout_config.get('components', [])
            for comp in components:
                # truncate config for PDF
                cfg = str(comp.get('config', {}))
                if len(cfg) > 50: cfg = cfg[:47] + "..."
                data.append([comp.get('label', 'Untitled'), comp.get('type', 'Unknown'), cfg])
                
            t = Table(data, colWidths=[150, 100, 250])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1A4D2E")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            elements.append(t)
            
            doc.build(elements)
            response.write(buffer.getvalue())
            buffer.close()
            return response

        return Response({"error": "Invalid format requested"}, status=status.HTTP_400_BAD_REQUEST)
