# Generated by Django 4.2.27 on 2026-01-31 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('definition', models.TextField(help_text='Detailed explanation of what this indicator measures')),
                ('unit_type', models.CharField(choices=[('NUMBER', 'Number'), ('PERCENTAGE', 'Percentage'), ('CURRENCY', 'Currency'), ('BOOLEAN', 'Yes/No')], default='NUMBER', max_length=20)),
                ('direction', models.CharField(choices=[('INCREASING', 'Increasing is Good (e.g. Beneficiaries Reached)'), ('DECREASING', 'Decreasing is Good (e.g. Infection Rate)'), ('NEUTRAL', 'Neutral / Tracking Only')], default='INCREASING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorTarget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baseline_value', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('description', models.CharField(blank=True, help_text="e.g. 'End of Year 1 Target'", max_length=255)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='indicators.indicator')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_targets', to='projects.project')),
            ],
            options={
                'unique_together': {('indicator', 'project')},
            },
        ),
        migrations.CreateModel(
            name='IndicatorResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('notes', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_results', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='indicators.indicatortarget')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
