# Generated by Django 4.2.27 on 2026-01-31 14:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFrameNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('GOAL', 'Goal / Impact'), ('OUTCOME', 'Outcome'), ('OUTPUT', 'Output'), ('ACTIVITY', 'Activity')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='indicators.logframenode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logframe_nodes', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
