# Generated by Django 4.2.27 on 2026-01-31 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_logframenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatortarget',
            name='logframe_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_targets', to='indicators.logframenode'),
        ),
    ]
