# Generated by Django 4.2.27 on 2026-02-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_indicatortarget_logframe_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='disaggregation',
            field=models.JSONField(default=list, help_text="e.g. ['Gender', 'Age', 'Location']"),
        ),
        migrations.AddField(
            model_name='indicator',
            name='level',
            field=models.CharField(choices=[('IMPACT', 'Impact / Goal'), ('OUTCOME', 'Outcome'), ('OUTPUT', 'Output'), ('ACTIVITY', 'Activity')], default='OUTPUT', max_length=20),
        ),
    ]
