# Generated by Django 4.2.27 on 2026-02-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_frameworktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='category',
            field=models.CharField(choices=[('STANDARD', 'Standard (Operational)'), ('ESG_ENVIRONMENTAL', 'ESG - Environmental'), ('ESG_SOCIAL', 'ESG - Social'), ('ESG_GOVERNANCE', 'ESG - Governance'), ('CUSTOM', 'Custom')], default='STANDARD', max_length=30),
        ),
    ]
