# Generated by Django 4.2.27 on 2026-02-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_indicator_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorresult',
            name='disaggregated_data',
            field=models.JSONField(blank=True, default=dict, help_text="Breakdown data e.g. {'Male': 10, 'Female': 15}"),
        ),
    ]
