# Generated by Django 4.2.27 on 2026-02-04 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indicators', '0007_indicatorresult_disaggregated_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorresult',
            name='rejection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indicatorresult',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
