# Generated by Django 4.2.27 on 2026-02-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0008_indicatorresult_rejection_notes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorresult',
            options={'ordering': ['-date', '-created_at']},
        ),
    ]
