# Generated by Django 4.2.27 on 2026-02-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0009_alter_indicatorresult_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='formula_definition',
            field=models.TextField(blank=True, help_text='Template: {ind_id1} + {ind_id2}'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='qualitative_options',
            field=models.JSONField(blank=True, default=dict, help_text="e.g. {'PASS': 100, 'FAIL': 0}"),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit_type',
            field=models.CharField(choices=[('NUMBER', 'Number'), ('PERCENTAGE', 'Percentage'), ('CURRENCY', 'Currency'), ('BOOLEAN', 'Yes/No'), ('QUALITATIVE', 'Qualitative (e.g. Pass/Fail)'), ('FORMULA', 'Formula (Calculated)')], default='NUMBER', max_length=20),
        ),
    ]
