# Generated by Django 4.2.27 on 2026-02-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0010_indicator_formula_definition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='reporting_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual'), ('ONCE', 'Once (End of Project)')], default='MONTHLY', max_length=20),
        ),
    ]
