# Generated by Django 4.2.27 on 2026-02-05 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_strategictheme_project_themes'),
        ('indicators', '0011_indicator_reporting_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='theme',
            field=models.ForeignKey(blank=True, help_text='Link to Strategic Theme for auto-assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standard_indicators', to='projects.strategictheme'),
        ),
    ]
