# Generated by Django 4.2.27 on 2026-02-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalMapLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('layer_type', models.CharField(choices=[('WMS', 'Web Map Service'), ('XYZ', 'XYZ Tile Layer'), ('GEOJSON', 'GeoJSON Data')], max_length=10)),
                ('url', models.URLField(help_text='URL template for tiles or API endpoint for data')),
                ('api_key_env_var', models.CharField(blank=True, help_text='Environment variable name for the API key (if required)', max_length=100, null=True)),
                ('attribution', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
