# Generated by Django 4.2.27 on 2026-02-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('CONTRACTOR', 'Contractor'), ('PARTNER', 'Partner'), ('VENDOR', 'Vendor')], max_length=20),
        ),
    ]
