# Generated by Django 4.2.27 on 2026-02-02 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_widgets', models.JSONField(default=list, help_text='List of widget IDs to hide')),
                ('time_range', models.CharField(choices=[('7d', 'Last 7 Days'), ('30d', 'Last 30 Days'), ('90d', 'Last 90 Days'), ('1y', 'Last Year'), ('all', 'All Time')], default='30d', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_pref', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Preference',
                'verbose_name_plural': 'Dashboard Preferences',
            },
        ),
    ]
