# Generated by Django 4.2.27 on 2026-02-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dashboardpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('COMMENT', 'Comment')], max_length=20),
        ),
    ]
