# Generated by Django

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_activitylog_action'),
    ]

    operations = [
        # Step 1: Create Permission model
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="e.g., 'view_dashboard', 'create_project'", max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('module', models.CharField(help_text="e.g., 'dashboard', 'projects', 'evaluations'", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['module', 'code'],
            },
        ),
        
        # Step 2: Create Role model
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='core.permission')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        
        # Step 3: Rename old role field to legacy_role
        migrations.RenameField(
            model_name='user',
            old_name='role',
            new_name='legacy_role',
        ),
        
        # Step 4: Make legacy_role nullable
        migrations.AlterField(
            model_name='user',
            name='legacy_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('PM', 'Project Manager'), ('INSPECTOR', 'Inspector'), ('FINANCE', 'Finance'), ('CONTRACTOR', 'Contractor')], max_length=20, null=True),
        ),
        
        # Step 5: Add new role field as ForeignKey
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.role'),
        ),
    ]
