# Generated by Django 4.2.27 on 2026-02-03 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_seed_permissions_and_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('TASK_ASSIGNED', 'Task Assigned'), ('COMMENT_ADDED', 'Comment Added'), ('STATUS_CHANGED', 'Status Changed'), ('APPROVAL_NEEDED', 'Approval Needed'), ('DEADLINE_APPROACHING', 'Deadline Approaching')], default='INFO', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_model', models.CharField(blank=True, help_text="e.g., 'Project', 'Inspection'", max_length=50)),
                ('related_id', models.CharField(blank=True, help_text='UUID of related object', max_length=100)),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate when clicked', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='core_notifi_recipie_aeffaf_idx'), models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx')],
            },
        ),
    ]
