# Generated by Django 4.2.27 on 2026-02-04 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(help_text="e.g. 'portfolio', 'financial', 'impact'", max_length=50)),
                ('report_name', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='WEEKLY', max_length=20)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel'), ('PDF', 'PDF')], default='PDF', max_length=10)),
                ('recipients', models.JSONField(default=list, help_text='List of email addresses')),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Filter criteria for the report')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_run_at'],
            },
        ),
    ]
