# Generated by Django 4.2.27 on 2026-02-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_scheduledreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCESS', 'Success'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('TASK_ASSIGNED', 'Task Assigned'), ('COMMENT_ADDED', 'Comment Added'), ('STATUS_CHANGED', 'Status Changed'), ('APPROVAL_NEEDED', 'Approval Needed'), ('DEADLINE_APPROACHING', 'Deadline Approaching'), ('DAILY_DIGEST', 'Daily Digest')], default='INFO', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='legacy_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('PM', 'Project Manager'), ('INSPECTOR', 'Inspector'), ('FINANCE', 'Finance'), ('CONTRACTOR', 'Contractor'), ('IMPACT_ANALYST', 'Impact Analyst')], max_length=20, null=True),
        ),
    ]
