# Generated by Django 4.2.29 on 2026-03-30 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_contract_enhancement'),
        ('core', '0011_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('category', models.CharField(choices=[('CONTRACT', 'Contract'), ('REPORT', 'Report'), ('EVALUATION', 'Evaluation'), ('FINANCIAL', 'Financial'), ('LEGAL', 'Legal'), ('PHOTO', 'Photo'), ('CORRESPONDENCE', 'Correspondence'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Public documents appear on the transparency page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.contract')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['project', 'category'], name='core_docume_project_8ee71e_idx'), models.Index(fields=['is_public'], name='core_docume_is_publ_23d639_idx')],
            },
        ),
    ]
