# Generated by Django 4.2.29 on 2026-03-31 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_document_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Users with this role have full system access (maker-checker bypass, admin APIs)'),
        ),
    ]
